# Generated by Django 6.0 on 2025-12-18 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement', '0001_initial'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likescomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likespost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posts'),
        ),
        migrations.AddField(
            model_name='likespost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='likescomment',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_liking_comment'),
        ),
        migrations.AddConstraint(
            model_name='likespost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_liking_post'),
        ),
    ]
