# Generated by Django 4.2.26 on 2025-12-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classrooms.class'),
            preserve_default=False,
        ),
    ]
