# Generated by Django 6.0 on 2025-12-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='class_id',
            new_name='course_id',
        ),
    ]
