# Generated by Django 4.2.26 on 2025-12-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('posting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='class_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
