# Generated by Django 4.2.26 on 2025-12-08 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posts')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'Comments',
                'ordering': ['-reply_time'],
            },
        ),
        migrations.CreateModel(
            name='CommentHierarchyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('descendant_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_comment', to='comments.comments')),
                ('original_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_comment', to='comments.comments')),
            ],
            options={
                'verbose_name': 'Comment Hierarchy',
                'verbose_name_plural': 'Comment Hierarchies',
                'db_table': 'CommentHierarchyTable',
            },
        ),
    ]
