# Generated by Django 6.0 on 2025-12-12 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posts'),
        ),
        migrations.AddField(
            model_name='commenthierarchytable',
            name='descendant_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_comment', to='comments.comments'),
        ),
        migrations.AddField(
            model_name='commenthierarchytable',
            name='original_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_comment', to='comments.comments'),
        ),
    ]
