# Generated by Django 4.2.26 on 2025-12-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commenthierarchytable',
            table='CommentHierarchy',
        ),
    ]
