# Generated by Django 6.0 on 2025-12-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commenthierarchytable',
            table='CommentHierarchy',
        ),
    ]
