# Generated by Django 4.2.26 on 2025-12-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('instructor', 'Instructor'), ('student', 'Student'), ('author', 'Author')], default='user', max_length=20),
        ),
    ]
